---
- name: todo-backend
  docker_container:
    name: todo-backend
    image: moredip/todo-backend-site
    pull: true
    command: "build serve"
    env:
      TZ: "{{ nas_timezone }}"
      # TODO fix this. I want the ids of the ansible_user
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: "traefik"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.todo_backend.rule: "Host(`todo-backend.{{ nas_domain }}`)"
      # traefik.http.routers.todo_backend.middlewares: "authelia@docker"
      traefik.http.routers.todo_backend.tls: "true"
      traefik.http.routers.todo_backend.tls.certresolver: "letsencrypt"
      traefik.http.services.todo_backend.loadbalancer.server.port: "4567"
