---
- name: "Ensure jellyfin dataset exists"
  community.general.zfs:
    name: "{{ jellyfin_dataset }}"
    state: present

- name: "Ensure jellyfin dir has correct permissions"
  file:
    path: "{{ jellyfin_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rwx,o=rx

- name: "Ensure jellyfin cache dir exists"
  community.general.zfs:
    name: "{{ jellyfin_dataset }}/cache"
    state: present
    extra_zfs_properties:
      com.sun:auto-snapshot: "false"

- name: "Ensure jellyfin cache has correct permissions"
  file:
    path: "{{ jellyfin_dir }}/cache"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rwx,o=rx

- name: jellyfin
  docker_container:
    name: jellyfin
    image: jellyfin/jellyfin
    pull: true
    volumes:
      - "{{ jellyfin_dir }}:/config:rw"
      - "{{ jellyfin_dir }}/cache:/config/cache:rw"
      - "{{ tvshows_dir }}:/tvshows:rw"
      - "{{ movies_dir }}:/movies:rw"
    ports:
      - 8096:8096
    env:
      TZ: "{{ nas_timezone }}"
      # TODO fix this. I want the ids of the ansible_user
      PUID: "1000"
      PGID: "1000"
      JELLYFIN_PublishedServerUrl: "https://jellyfin.{{ nas_domain }}"
    device_requests:
      - driver: nvidia
        count: -1
        capabilities:
          - - gpu
            - compute
            - utility
    networks:
      - name: "traefik"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.jellyfin.rule: "Host(`jellyfin.{{ nas_domain }}`)"
      traefik.http.routers.jellyfin.middlewares: "authelia@docker"
      traefik.http.routers.jellyfin.tls: "true"
      traefik.http.routers.jellyfin.tls.certresolver: "letsencrypt"
      traefik.http.services.jellyfin.loadbalancer.server.port: "8096"
      traefik.http.services.jellyfin.loadbalancer.passHostHeader: "true"
