---
- hosts: nas
  become: yes
  pre_tasks:
    - name: Include vars
      include_vars:
        dir: vars
    - import_tasks: tasks/zfs-dataset.yml
  roles:
    - role: update
      keep_packages_updated: yes
    - role: weareinteractive.ufw
      ufw_rules:
        - logging: on
        - direction: incoming
          default: deny
        - direction: outgoing
          default: allow
        # SSH port for endlessh
        - rule: limit
          to_port: 22
          proto: tcp
        # Real SSH port
        - rule: limit
          to_port: "{{ ansible_port }}"
          proto: tcp
        # Website
        - rule: allow
          to_port: 80
          proto: tcp
        - rule: allow
          to_port: 443
          proto: tcp
    - role: robertdebock.sysctl
      sysctl_items:
        - name: net.ipv4.conf.all.accept_redirects
          value: 0
        - name: net.ipv6.conf.all.accept_redirects
          value: 0
        - name: net.ipv4.conf.all.send_redirects
          value: 0
        - name: net.ipv4.conf.all.accept_source_route
          value: 0
        - name: net.ipv6.conf.all.accept_source_route
          value: 0
    - role: jnv.unattended-upgrades
      unattended_automatic_reboot: yes
      unattended_automatic_reboot_time: 03:00
    - role: oefenweb.fail2ban
    - role: geerlingguy.ntp
      ntp_timezone: "{{ nas_timezone }}"
    - role: geerlingguy.docker
      docker_users:
        - "{{ ansible_user }}"
    - role: docker-python
    - role: zfs-auto-snapshot
    # vpn is early so that it can be up before dependencies.
    - role: vpn
    - role: ddclient
    - role: endlessh
    - role: watchtower
    - role: authelia
    - role: traefik
    - role: openspeedtest
    - role: transmission
    - role: uptime-kuma
    - role: zfs-health
    - role: gitea
    - role: nix-auto-seeder
