---
- hosts: nas
  roles:
    - role: weareinteractive.ufw
      become: yes
    - role: jnv.unattended-upgrades
      become: yes
    - role: geerlingguy.docker
      become: yes

  vars:
    ufw_rules:
      - logging: on
      - direction: incoming
        default: deny
      - direction: outgoing
        default: allow
      # SSH port for endlessh
      - rule: limit
        to_port: 22
        proto: tcp
      # Real SSH port
      - rule: limit
        to_port: "{{ ansible_port }}"
        proto: tcp
      # - rule: allow
      #   to_port: 80
      #   proto: tcp
      # - rule: allow
      #   to_port: 443
      #   proto: tcp
    unattended_automatic_reboot_time: 03:00
