---
- hosts: nas
  become: true
  tasks:
    - name: Warning!
      debug:
        msg: "This playbook will repermission ALL existing data in the dpool. If this is not what you want, exit now."

    - name: 20s to change your mind...
      pause:
        seconds: 20

    - name: "Permission share data"
      file:
        path: "/mnt/dpool"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "u=rwx,g=rwx,o=rx"
        recurse: true
