---
roles:
  - name: geerlingguy.pip

  - name: geerlingguy.docker

  - name: weareinteractive.ufw

  - name: hifis.unattended-upgrades

  - name: oefenweb.fail2ban

  - name: robertdebock.sysctl

  - name: geerlingguy.ntp

collections:
  - name: community.general
