---
- name: geerlingguy.docker
  version: 4.1.1

- name: weareinteractive.ufw
  version: 2.0.1

- name: jnv.unattended-upgrades
  version: v1.12.1

- name: oefenweb.fail2ban
  version: v3.5.1

- name: robertdebock.sysctl
  version: 2.1.2

- name: geerlingguy.ntp
  version: 2.3.0
