mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: False

cameras:
  rhea_cam:
    enabled: false
    ffmpeg:
      inputs:
        - path: rtsp://10.0.10.10:554/rtsp # <----- The stream you want to use for detection
          roles:
            - detect
    detect:
      enabled: false # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720

version: 0.14
