mqtt:
  enabled: false

tls:
  enabled: false

auth:
  enabled: false

# detectors:
#   tensorrt:
#     type: tensorrt
#     device: 0

birdseye:
  mode: continuous

# model:
#   path: /config/model_cache/tensorrt/yolov7-320.trt
#   input_tensor: nchw
#   input_pixel_format: rgb
#   width: 320
#   height: 320

cameras:
  rhea_cam:
    enabled: true
    ffmpeg:
      # hwaccel_args: preset-nvidia-h264
      inputs:
        - path: rtsp://{{ frigate_config.username }}:{{ frigate_config.password }}@{{ frigate_config.ip }}:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
    # TODO: load with onvif tool and create new acount. Theoretically will fix.
    # onvif:
    #   host: {{ frigate_config.ip }}
    #   port: 80
    #   user: {{ frigate_config.username }}
    #   password: {{ frigate_config.password }}
    record:
      enabled: true
      retain:
        days: 30
        mode: all

    motion:
      enabled: true
      # Block out the camera timestamp.
      mask: 0.75,0.036,0.971,0.026,0.971,0.099,0.749,0.09

    # No need for silly people alerts
    review:
      alerts:
        labels: []

version: 0.14
