---
- name: watchtower
  docker_container:
    name: watchtower
    image: containrrr/watchtower
    pull: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    env:
      TZ: "{{ nas_timezone }}"
    # TODO: look into notifications
    # Run at 5am everyday
    command: '--cleanup --schedule "0 0 5 * * *"'
    restart_policy: unless-stopped

    # Disable watchtower for now. It keeps breaking other containers
    state: absent
