---
- name: "Ensure ddclient dataset exists"
  community.general.zfs:
    name: "{{ ddclient_dataset }}"
    state: present

- name: "Ensure ddclient dir has correct permissions"
  file:
    path: "{{ ddclient_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx

- name: ddclient
  docker_container:
    name: ddclient
    image: linuxserver/ddclient
    pull: true
    volumes:
      - "{{ ddclient_dir }}:/config:rw"
    env:
      TZ: "{{ nas_timezone }}"
      # TODO fix this. I want the ids of the ansible_user
      PUID: "1000"
      PGID: "1000"
    restart_policy: unless-stopped

# Creating the container seems to generate a default config.
# This way we overwrite it after it is generated.
- name: Set ddclient config
  template:
    src: config.j2
    dest: "{{ ddclient_dir }}/ddclient.conf"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rw
  notify: restart ddclient
