---
theme: dark
default_redirection_url: "https://{{ nas_domain }}"
jwt_secret: "{{ authelia_secret }}"

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  networks:
    - name: internal
      networks:
        - 192.168.1.0/24

  rules:
    # No security
    - domain: "health.{{ nas_domain }}"
      policy: bypass

    # Light security
    - domain: "speed.{{ nas_domain }}"
      networks: internal
      policy: bypass
    - domain: "speed.{{ nas_domain }}"
      policy: one_factor

    # High security
    - domain:
        - "traefik.{{ nas_domain }}"
        - "torrent.{{ nas_domain }}"
      networks: internal
      subject: "group:admin"
      policy: one_factor
    - domain:
        - "traefik.{{ nas_domain }}"
        - "torrent.{{ nas_domain }}"
      subject: "group:admin"
      policy: two_factor

session:
  domain: "{{ nas_domain }}"
  expiration: 1h
  inactivity: 15m

regulation:
  max_retries: 3
  find_time: 2m
  ban_time: 5m

storage:
  encryption_key: "{{ authelia_encryption_key }}"
  local:
    path: /config/db.sqlite3

notifier:
  smtp:
    host: smtp.gmail.com
    port: 587
    username: "{{ nas_email }}"
    password: "{{ nas_email_password }}"
    sender: "{{ nas_email }}"
