---
- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Remove docker-py python module
  pip:
    name: docker-py
    state: absent

- name: Install docker python module
  pip:
    name: docker
    state: present
