---
- name: nordvpn
  docker_container:
    name: nordvpn
    image: bubuntux/nordlynx
    pull: true
    capabilities:
      - NET_ADMIN
    env:
      TZ: "{{ nas_timezone }}"
      PRIVATE_KEY: "{{ nordvpn_private_key|quote }}"
      QUERY: "{{ nordvpn_query }}"
      NET_LOCAL: "172.17.0.0/16,192.168.1.0/24"
    networks:
      - name: "traefik"
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv6.conf.all.disable_ipv6: "1"
    restart_policy: unless-stopped
