---
- name: "Ensure prowlarr dataset exists"
  community.general.zfs:
    name: "{{ prowlarr_dataset }}"
    state: present

- name: "Ensure prowlarr dir has correct permissions"
  file:
    path: "{{ prowlarr_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rwx,o=rx

- name: prowlarr
  docker_container:
    name: prowlarr
    image: linuxserver/prowlarr:develop
    pull: true
    volumes:
      - "{{ prowlarr_dir }}:/config:rw"
    env:
      TZ: "{{ nas_timezone }}"
      # TODO fix this. I want the ids of the ansible_user
      PUID: "1000"
      PGID: "1000"
    network_mode: "container:vpn"
    restart_policy: unless-stopped
