---
- name: "Ensure sonarr dataset exists"
  community.general.zfs:
    name: "{{ sonarr_dataset }}"
    state: present

- name: "Ensure sonarr dir has correct permissions"
  file:
    path: "{{ sonarr_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rwx,o=rx

- name: sonarr
  docker_container:
    name: sonarr
    image: linuxserver/sonarr
    pull: true
    volumes:
      - "{{ sonarr_dir }}:/config:rw"
      - "{{ downloads_dir }}:/downloads:rw"
      - "{{ tvshows_dir }}:/tv:rw"
    env:
      TZ: "{{ nas_timezone }}"
      # TODO fix this. I want the ids of the ansible_user
      PUID: "1000"
      PGID: "1000"
    network_mode: "container:vpn"
    networks:
      - name: "traefik"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr.rule: "Host(`sonarr.{{ nas_domain }}`)"
      traefik.http.routers.sonarr.middlewares: "authelia@docker"
      traefik.http.routers.sonarr.tls: "true"
      traefik.http.routers.sonarr.tls.certresolver: "letsencrypt"
      traefik.http.services.sonarr.loadbalancer.server.port: "8989"
