---
- name: "Ensure bazarr dataset exists"
  community.general.zfs:
    name: "{{ bazarr_dataset }}"
    state: present

- name: "Ensure bazarr dir has correct permissions"
  file:
    path: "{{ bazarr_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rwx,o=rx

- name: bazarr
  docker_container:
    name: bazarr
    image: linuxserver/bazarr
    pull: true
    volumes:
      - "{{ bazarr_dir }}:/config:rw"
      - "{{ downloads_dir }}:/downloads:rw"
      - "{{ movies_dir }}:/movies:rw"
      - "{{ tvshows_dir }}:/tv:rw"
    env:
      TZ: "{{ nas_timezone }}"
      # TODO fix this. I want the ids of the ansible_user
      PUID: "1000"
      PGID: "1000"
    network_mode: "container:vpn"
    restart_policy: unless-stopped
