---
- name: openspeedtest
  docker_container:
    name: openspeedtest
    image: openspeedtest/latest
    pull: true
    env:
      TZ: "{{ nas_timezone }}"
    networks:
      - name: "traefik"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.openspeedtest.rule: "Host(`speed.{{ nas_domain }}`)"
      traefik.http.routers.openspeedtest.middlewares: "authelia@docker"
      traefik.http.routers.openspeedtest.tls: "true"
      traefik.http.services.openspeedtest.loadbalancer.server.port: "3000"
