entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        domains:
          main: "{{ nas_domain }}"
          sans:
            - "*.{{ nas_domain }}"
providers:
  providersThrottleDuration: 2s
  docker:
    exposedbydefault: false
    watch: true
api:
  dashboard: true
log:
  level: DEBUG
ping:
  manualRouting: true
certificatesResolvers:
  letsencrypt:
    acme:
      email: "{{ letsencrypt_email }}"
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
