---
- name: "Ensure syncthing dataset exists"
  community.general.zfs:
    name: "{{ syncthing_dataset }}"
    state: present

- name: "Ensure syncthing dir has correct permissions"
  file:
    path: "{{ syncthing_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rwx,o=rx

- name: syncthing
  docker_container:
    name: syncthing
    image: linuxserver/syncthing
    pull: true
    volumes:
      - "{{ syncthing_dir }}:/config:rw"
      - "{{ sync_dir }}:/sync:rw"
    env:
      TZ: "{{ nas_timezone }}"
      # TODO fix this. I want the ids of the ansible_user
      PUID: "1000"
      PGID: "1000"
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart_policy: unless-stopped
