---
- name: roc-todos
  docker_container:
    name: roc-todos
    image: bhansconnect/roc-todos
    pull: true
    env:
      TZ: "{{ nas_timezone }}"
      # TODO fix this. I want the ids of the ansible_user
      PUID: "1000"
      PGID: "1000"
      BASE_URL: "https://roc-todos.{{ nas_domain }}"
      RUST_LOG: "debug"
    # This is to limit the todo db size.
    storage_opts:
      size: "1G"
    networks:
      - name: "traefik"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.roc_todos.rule: "Host(`roc-todos.{{ nas_domain }}`)"
      # traefik.http.routers.roc_todos.middlewares: "authelia@docker"
      traefik.http.routers.roc_todos.tls: "true"
      traefik.http.routers.roc_todos.tls.certresolver: "letsencrypt"
      traefik.http.services.roc_todos.loadbalancer.server.port: "3000"
